import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Browser Extensions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
      </Head>
      <main className={styles.main}>
        <div style={{textAlign: 'center', padding: '50px 20px'}}>
          <h1>Browser-Extensions</h1>
          <hr />
          <h6>Repo for hosting all the browser extension related static pages</h6>
        </div>
      </main>
    </>
  )
}
